# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumpnail',
            field=models.ImageField(default='thumpnail/None/default_thump.png', upload_to='thumpnails'),
        ),
    ]
