# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approvedBy',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='unapprovedBy',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='dislikedBy',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='likedBy',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='rated1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='rated2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='rated3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='rated4',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='rated5',
            field=models.TextField(default=''),
        ),
    ]
