# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0005_auto_20170506_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='unapprovedBy',
            new_name='disapprovedBy',
        ),
        migrations.RemoveField(
            model_name='video',
            name='dislikedBy',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likedBy',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rated1',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rated2',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rated3',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rated4',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rated5',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='video',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='video',
            name='rating_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default='no-review', max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumpnail',
            field=models.FileField(default='thumpnail/None/default_thump.png', upload_to='thumpnails'),
        ),
    ]
