# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0007_auto_20170524_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='overall',
        ),
    ]
