# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0008_remove_video_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.CharField(default='', max_length=400),
        ),
    ]
