# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0009_profile_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
