# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0010_profile_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribes',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
