# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0011_auto_20170526_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.CharField(default='', max_length=4000000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribes',
            field=models.CharField(default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=94),
        ),
    ]
