# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0012_auto_20170529_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=46),
        ),
    ]
