# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0014_video_th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='th',
            field=models.BooleanField(default=True),
        ),
    ]
