# Generated by Django 4.2.3 on 2023-07-23 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="videos")),
                ("title", models.CharField(max_length=46)),
                ("tags", models.CharField(default="", max_length=200)),
                ("description", models.TextField(max_length=3000)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("rating_counter", models.IntegerField(default=0)),
                (
                    "thumbnail",
                    models.FileField(
                        default="thumbnail/None/default_thumb.png",
                        upload_to="thumbnails",
                    ),
                ),
                ("th", models.BooleanField(default=True)),
                ("views", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default="no-review", max_length=1000)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
                ),
                ("approvedBy", models.TextField(default="")),
                ("disapprovedBy", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ur8_app.video"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="avatar/None/default_avatar.png", upload_to="avatars"
                    ),
                ),
                ("notifications", models.CharField(default="", max_length=4000000)),
                ("count", models.IntegerField(default=0)),
                ("subscribes", models.CharField(default="", max_length=40000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
