# Generated by Django 4.2.3 on 2023-07-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ur8_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="notifications",
            field=models.CharField(default="Welcome,", max_length=4000000),
        ),
    ]
